[package]
name = "cipher312"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nom = "8"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wit-bindgen = "0.47"

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
cbindgen = "0.29"
